[tool.poetry]
name = "twiner"
version = "0.1.0"
description = "CLI that helps you with notifications for your favorite streamers on Twitch.tv"
authors = ["febits <febits@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
